### ISSUE TITLE
[Request] Block calls from outside the country

### ISSUE THREAD

**Issue by Dyras** [x13a/Silence#1]
Hello! Any chance you could add an option to block calls from outside the country that the user currently lives in? I've never once in my life received a non-spam call from another country.

Thanks in advance!

**Comment by x13a** [comment]
Hello.

This app is working in the opposite direction. When you activate it, incoming calls from numbers that are not stored in your contacts will be blocked. Every toggle add some permit scope to bypass this filter. Simply saying it mimics Apple's [Silence Unknown Callers](https://support.apple.com/en-us/HT207099).

**Comment by Dyras** [comment]
Ah, I see (I was drunk last night so I'm blaming them)

If so, is there a chance you could add a switch for "Allow local numbers"? :)

**Comment by x13a** [comment]
Sorry, but I dislike it. There are many apps that implement such a wide filters like`Allow local numbers / Block foreign numbers`, maybe not relying on `Call Screening` API, but there are. In the future I may implement [STIR/SHAKEN](https://en.wikipedia.org/wiki/STIR/SHAKEN) check (requires android 11) and this will help you, of cause if your mobile provider have implemented these protocols.

**Comment by Dyras** [comment]
Ok :)

**Comment by x13a** [comment]
@Dyras , better later than never, your request was implemented) Will be available soon.

**Comment by x13a** [comment]
Done in recent version
