### ISSUE TITLE
Feature Request -  Allow and Block specific area code

### ISSUE THREAD

**Issue by altmank** [x13a/Silence#106]
The majority of my spam is 'neighborhood' spoofing where they mimic my phone numbers area code. I live in a different state from my cell area code so I have no legitimate reason to get local area code calls that are not Contacts.

But I still want to have calls ring from my current location area code as those tend to be legitimate.

I don't think I can accomplish a blacklist of one area code and a whitelist of another with current functionality. If not, I'd like to request that be added.

**Comment by x13a** [comment]
If some one will make it, I may merge it.
