### ISSUE TITLE
How to temporary disable blocking numbers not in my contacts?

### ISSUE THREAD

**Issue by altwarg** [x13a/Silence#108]
I would like to temporary disable all filtering for numbers. What I can do for now -- is to disable rules for Silence but not the Silence blocking feature itself.

**Comment by Ilithy** [comment]
You can use the quick tile to promptly activate/deactivate Silence

**Comment by altwarg** [comment]
@Ilithy doesn't it just disable call acceptance rules?

I had some case when with deactivated Silence incoming calls were blocked for me.

**Comment by Ilithy** [comment]
No the tile completely disables Silence, or enables it of course (I just checked).

 Strange, this has never happened to me, have you disabled battery optimization for Silence?
You'll have to check with @x13a if there is a bug.

**Comment by x13a** [comment]
> I had some case when with deactivated Silence incoming calls were still blocked for me.

Maybe you Phone app blocked them?
If you disable `Silence` all calls have to be allowed.

**Comment by altwarg** [comment]
I will check it again. Thanks for your reply.
Closing for now.
