### ISSUE TITLE
Unclear options

### ISSUE THREAD

**Issue by eagerfish** [x13a/Silence#112]
Options are unclear, it's never stated in the options menu if flipping a switch will **allow** or **deny** a number.

Let's take a look at the first option:
Contacted (OFF | ON)
Numbers you have contacted

If i flip the switch the app will **allow** numbers i have contacted OR **deny** numbers i have contacted? It's not clear.

It would be a lot more clear with a description like this:
**allow** numbers you have contacted
or
**don't block** numbers you have contacted

Perhaps another solution would be to add some sort of title to the options. Like `Allow:` and then the options. I don't really know which is better but i'm more geared towards more _descriptive_ descriptions, even if it's kinda repetitive.

**Comment by x13a** [comment]
Options are to allow something.

**Comment by eagerfish** [comment]
> Options are to allow something

Yes, it's implied in the changelogs, clearly stated in the readme file.
It isn't stated in the options menu, which is a design flaw.

Phone apps are generally aimed towards the general public, at everyone. That's why it's very important apps and his configurations are self-explanatory and not dependent in outside resources.

**Comment by owenh000** [comment]
@x13a, thanks for this very useful app.

I agree with @eagerfish. The user interface is not intuitive. While I suppose there are many different ways to make it more clear, I would like to suggest the following addition to the main text at the top:

>Activate Silence to avoid getting calls from people you do not know. This blocks phone numbers that are not saved in your contacts. Calls are also accepted from any of the categories enabled below.

Or, this might be better because it is more explicit and also explains how to access more settings:

>Activate Silence to avoid getting calls from people you do not know.
>
>All incoming calls will be rejected except for those in your contacts and the categories selected below. Long-hold a category to change the settings for that category (excluding STIR/SHAKEN). Long-hold the main toggle button for additional settings.

(What do the additional settings do?)

**Comment by x13a** [comment]
On the master branch, will be available soon, closing
