### ISSUE TITLE
Security/privacy use

### ISSUE THREAD

**Issue by rudolfmu** [x13a/Silence#114]
If I understand it correctly, Silence becomes the default handler for caller-id and spam. When Silence is running but not set to active, do you
- take the caller-id and dump it
or
-pass the caller-id to the original (Android) app?

The reason for me asking is that if you do not pass handling on, Silence even when not active would keep the caller-id from being sent to Google by their app. This would mean that Silence would also enhance privacy. It would then be worth running Silence even if it is not used for blocking.

**Comment by x13a** [comment]
If `Silence` is set as default caller-id and turned off, then:

```kotlin
if (!prefs.isServiceEnabled) {
    respondAllow(callDetails)
    return
}
```

But I do not think that it will give you any privacy benefits. There is also `None` option in default caller-id settings. Anyway if you really want Google to stop getting your data, you have to _de-google_ you device.

**Comment by x13a** [comment]
Closing on inactivity
