### ISSUE TITLE
Questions about the options

### ISSUE THREAD

**Issue by Efenstor** [x13a/Silence#124]
Hello and thanks _a lot_ for this wonderful nerve-saving app!
I have who questions:

1. If I turn on the main "Messages" switch but leave both "Inbox" and "Body" sub-options off what does it do? Does it control receiving _messages_ or only _calls_ from the numbers from messages?
2. Is the sub-option "Message" in "Contacted" mean that it allows calls from the numbers I have _ever_ sent messages to? Or there are some time limits, because the call list may be years long?

**Comment by x13a** [comment]
Hi,

Without ticking sub-options it does nothing.
_Messages ->Inbox_ - allow a call after the caller have send you a message (will make android database query)
_Messages ->Body_ - temporarily (48h) allow a call after the caller number was found inside incoming message text (will scan incoming messages, if found will add it to internal database)

_Contacted->Message_ - Yes, no limits. Will make android database query. I have not tested it will very long datasets. But nobody opened issue on this.
```kotlin
          cursor = ctx.contentResolver.query(
              Telephony.Sms.Sent.CONTENT_URI,
              arrayOf(Telephony.Sms._ID),
              "${Telephony.Sms.ADDRESS} = ?",
              arrayOf(phoneNumberUtil.format(
                  number,
                  PhoneNumberUtil.PhoneNumberFormat.E164,
              )),
              null,
          )
```

**Comment by Efenstor** [comment]
One more similar question: what do "Controller" and "Unknown numbers" options mean? I suppose unknown numbers is calls without caller ID, but "controller" is the term I never heard of.

**Comment by x13a** [comment]
_Unknown numbers_ - yes, it will allow calls from them
_Controller_ - is the broadcast receiver, it can be used to control _Silence_ with intents, useful for automation, like disable/enable _Silence_ and tick some it options from another apps

**Comment by x13a** [comment]
Internal database is used only for numbers from within incoming messages text for faster lookup. All other operations use android databases. After call screening makes a response, android system caches the result for around a minute. If the second repeated call will be in the cache interval, android system will make a response itself without Silence. This repeated calls have to be out of the cache interval.

**Comment by Ilithy** [comment]
> Messages->Body - temporarily (48h) allow a call after the caller number was found inside incoming message text (will scan incoming messages, if found will add it number to internal database)

Will it be possible in the future to add an option to control the retention time of the numbers in the internal database of the app?
Thanks

**Comment by x13a** [comment]
Yes, will add it in the next update.

**Comment by Ilithy** [comment]
Wonderful, thank you <3

**Comment by x13a** [comment]
> add an option to control the retention time of the numbers in the internal database

Done in recent version
