### ISSUE TITLE
No rejected calls in call log on Android 11

### ISSUE THREAD

**Issue by Efenstor** [x13a/Silence#125]
If I turn "Skip notification" on but leave "Skip call log" off it seems that the rejected calls do not appear in the recent calls list, or anywhere else. I just don't know if any call was rejected. At least that is on Android 11.

**Comment by x13a** [comment]
I will take a look in emulator thx, but the _dialer_ app may respect this flags or not. Try to check with another dialer, like Simple Dialer.

**Comment by Efenstor** [comment]
Just in case, I am using LineageOS 18 GSI, based on Android 11. As far as I'm aware it's using the unmodified 11's dialer.

**Comment by x13a** [comment]
https://github.com/x13a/Silence/issues/34

**Comment by Efenstor** [comment]
Closing the issue as "no fix".
