### ISSUE TITLE
Exit settings

### ISSUE THREAD

**Issue by Ilithy** [x13a/Silence#127]
Hi; _(I take the opportunity, really excellent update, thank you very much)_ I noticed a small annoyance _(neither bug nor real trouble)_,
if you click on the cog wheel you logically access the app settings;
however to return to the main screen it is necessary to do appear the left side panel, then click on "main", it's not very intuitive _(but not impossible either)_.

is it possible to have the click on the wheel display the options, then a second click the masks? _(or another method)_

Thanks.

**Comment by x13a** [comment]
Thank you very much) Will fix this in the next update.

**Comment by x13a** [comment]
Done in recent version

**Comment by x13a** [comment]
Thank you very much) Will fix this in the next update.
