### ISSUE TITLE
On/Off button

### ISSUE THREAD

**Issue by guillaumeboehm** [x13a/Silence#136]
Hi thanks for the app!

Little accessibility issue.
The main view on/off type button is always confusing to me, I can never tell if the text displayed is the current state, or the action the button will trigger.

I would suggest either a clear color change or a clearer text (like Deactivate and Activate for an action or "Silence is ON/OFF" for the state)

**Comment by guillaumeboehm** [comment]
I see, yeah in my case it is ON/OFF and with my theme there is no decoration changes whatsoever on toggle so it's quite confusing... But the constraint totally makes sense. I guess I'll just put up with it.

**Comment by Ilithy** [comment]
it's strange that you don't have this color change depending on the state, on my three devices it works (OxygenOS 11.1.2.2 - android 11, ColorOS 12 - android 12 and GrapheneosOS - android 12), the first I have a cian color bar, the second and third support monet, and adapt the accent color (and indeed, depending on the color, it's very light, and difficult to discern).

_I find that the On/Off (present on all) is less elegant than the previous button but is really important, I think not ;)_

**Comment by guillaumeboehm** [comment]
Did you try with a phone in dark mode? Mine is, I suppose this is why.

**Comment by Ilithy** [comment]
I'm not a developer honestly I don't know if this can impact this, I quickly tested with the dark mode activated, it did not change the colors;
I attach the captures of two of my peripherals, you will notice that for the first, the color is less intense (I mean less noticeable), it comes from the color of my screen background.  
  
  


<a href="https://ibb.co/64zJr4V"><img src="https://i.ibb.co/tbgPQbk/Screenshot-20220717-105520.jpg" alt="Screenshot-20220717-105520" border="0"></a>
  

<a href="https://ibb.co/YpnyVtL"><img src="https://i.ibb.co/t8jx1bJ/Screenshot-20220717-105332.png" alt="Screenshot-20220717-105332" border="0"></a>

**Comment by x13a** [comment]
OK, playing a bit with it, I think I have found a solution to make this button "great again". Thank you, @guillaumeboehm  & @Ilithy )
