### ISSUE TITLE
Proposal - Presentation screenshots

### ISSUE THREAD

**Issue by Ilithy** [x13a/Silence#147]
Hello, I don't know if you will like the idea, but I propose to make you a small presentation image of your application (for Github) and captures for the application store (such as Fdroid), nothing crazy, here is a first draft:

**For Github (or others)**

![Global Silence Presentation(1)(1)](https://user-images.githubusercontent.com/36798218/180013421-1458be5b-5cee-42d2-9b5f-bd8258a76e0e.png)

**For app store (or others):**

![Samsung Galaxy S20 Ultra(1)](https://user-images.githubusercontent.com/36798218/180013576-ec5cc1ef-8c13-4944-a555-e35e417351b8.png)
![Samsung Galaxy S20 Ultra](https://user-images.githubusercontent.com/36798218/180013587-fb58a2a0-a3ee-4f9b-9ea9-09edfef47a15.png)
![Samsung Galaxy S20 Ultra(2)](https://user-images.githubusercontent.com/36798218/180013592-5faeaab4-262a-468a-8ab5-1d7101c80e70.png)

If you're not interested, just close the issue (with my apologies for the inconvenience), if you want to see changes made, please let me know.

PS, from their transmission, these images are considered free of rights and use.

**Comment by x13a** [comment]
Hey,

Like your idea, thanks) Will your make a PR?

**Comment by Ilithy** [comment]
with pleasure, I take care of it quickly, thank you to you I will edit another series of captures, with additional parameters, for a more complete presentation in image, I will propose this to you tomorrow

**Comment by Ilithy** [comment]
Done on #149 
When the screenshots (or the presentation) are no longer useful (after additions/modifications on the app) and if I do not directly offer you replacements, do not hesitate to leave me a message here, I will make the modifications, and you would pass them on (via a PR).
thank you.
