### ISSUE TITLE
Possible to block all numbers starting with "+"?

### ISSUE THREAD

**Issue by githupper** [x13a/Silence#163]
Hi,

I would like to know if there is any way to setup in Silence to block any numbers that starts with "+65" but yet allows all numbers with "65" to pass through undisturbed.

Thank you

**Comment by x13a** [comment]
Hi,

For now there is no a such option. Does not these numbers are the same?

**Comment by githupper** [comment]
Hi. In my country, due to large number of scammers faking their caller-ID to pretend to be local numbers in order to masquerade themselves as govt agencies, police and the likes, the telecom regulator enforce a "+" for all foreign numbers in their caller-ID. Hence when we receive any calls with a +65, we know for sure it's 100% a scammer as all local numbers would not have a "+65" but rather "65" only.

This is one of the way out telecom regulator is helping in the fight against scammers and it works very well except I would like to automate the rejection of such numbers using Silence.

**Comment by x13a** [comment]
Got it, will add this.

**Comment by githupper** [comment]
Much thanks and very much looking forward to it!

**Comment by x13a** [comment]
@githupper done in the recent version

**Comment by githupper** [comment]
Appreciate the update! Will test it out ASAP!

**Comment by x13a** [comment]
Closing on inactivity
