### ISSUE TITLE
Feature request - Time between call attempts (burst protection)

### ISSUE THREAD

**Issue by Efenstor** [x13a/Silence#164]
It would be great if there would be a possibility to have a protection against automated redialing. For example, additional option could be added to the "Repeated" function, which sets the minimum time between incoming calls (from the same number). If redials are coming one after another too quickly then there is a great possibility is the automated dialer, a real person always waits a little if it's busy before trying again. So if the protection is activated no matter how many more dial attempts will be made they all will be rejected until there will be a long delay (may be the same as "Minutes"? or a dedicated value) between them.

**Comment by x13a** [comment]
As I remember there is a cache interval something like a minute (1m). Call screening service does not get repeated calls from the same number at this interval.

**Comment by x13a** [comment]
Done in the recent version.

**Comment by x13a** [comment]
I added _the minimum time between incoming calls (from the same number)_ in repeated check. Do not understand what you mean by

> So if the protection is activated no matter how many more dial attempts will be made they all will be rejected until there will be a long delay (may be the same as "Minutes"? or a dedicated value) between them.

**Comment by Efenstor** [comment]
> I added _the minimum time between incoming calls (from the same number)_ in repeated check. Do not understand what you mean by
> 
> > So if the protection is activated no matter how many more dial attempts will be made they all will be rejected until there will be a long delay (may be the same as "Minutes"? or a dedicated value) between them.

Thank you! I meant the same thing as you've implemented )
