### ISSUE TITLE
skip log not working on android 12

### ISSUE THREAD

**Issue by smazboy** [x13a/Silence#166]
Hello!
The skip log option does not work on android 12. I can still see the blocked calls in the phone call log

**Comment by x13a** [comment]
Hello,

It depends on the app that is showing you a call log. When you set skip call log, numbers anyway will be added to call log database, but will have a flag, that they should not be shown.

**Comment by x13a** [comment]
I pass these params in response per documentation.  
https://developer.android.com/reference/kotlin/android/telecom/CallScreeningService.CallResponse.Builder#setskipcalllog
There was an issue about call log and notifications, when I have played with these params. Do not remember if it was working.

**Comment by x13a** [comment]
Closing on inactivity
