### ISSUE TITLE
Skip notification option not working

### ISSUE THREAD

**Issue by guillaumeboehm** [x13a/Silence#167]
Hi, not sure if this is an issue in your app or not, but I have the 'skip notification' option toggled, yet I'm still getting the "This number tried to contact you..." message.
As this is not just a notification but rather a message, I'm not sure if your option is meant to prevent it... If not do you think you'd be able to prevent these messages?

**Comment by x13a** [comment]
Hi,

Please post a screenshot.

**Comment by guillaumeboehm** [comment]
As the message is in French even though my phone is in English I'm thinking this might be from my from my provider...
![msg](https://user-images.githubusercontent.com/12833794/185956642-93b893a2-ee05-438b-bdff-277c2082018c.jpg)
![log](https://user-images.githubusercontent.com/12833794/185956646-c9fe067d-0f9e-4d29-bbbe-259f4554487e.jpg)

**Comment by guillaumeboehm** [comment]
Okay thanks, I'll try things out with my friend's phone tomorrow.

**Comment by x13a** [comment]
@guillaumeboehm any progress?

**Comment by guillaumeboehm** [comment]
oooh yep yep sorry I was a bit busy and forgot to come back to you.
So yeah I tested it out a little bit and it seems that having the "Reject call" option set was causing this. I had a couple calls since deactivating it and haven't had the messages. Maybe it could be interesting to signal that depending on your provider this option could cause you to receive "Missed call" messages then ?

**Comment by x13a** [comment]
Good to know that. Cause it is carrier configuration, maybe late. Closing.
