### ISSUE TITLE
Feature : Block Spam SMS

### ISSUE THREAD

**Issue by Github-contribute** [x13a/Silence#178]
Block SMS Spam through Header. Some Apps Block SMS in Organised Way. So, It helps to Reduce Most Spam Messages. I Attached photos for better understanding.
@x13a 

![SMS Spam](https://user-images.githubusercontent.com/106362356/189283655-47de1a99-8577-4b3b-b6a1-d7b08eca0d5c.jpg)
![SMS](https://user-images.githubusercontent.com/106362356/189283673-553cbac1-d8f8-4b7b-be38-5c64a9c520dd.png)

**Comment by x13a** [comment]
Android does not have API for this. Closing
