### ISSUE TITLE
Add SMS Spam Filter

### ISSUE THREAD

**Issue by Github-contribute** [x13a/Silence#180]
No Api Needed or no Internet needed. (I just turn off internet permission through firewall works great )
@x13a 

Just check out this app
https://play.google.com/store/apps/details?id=com.mezo

![1](https://user-images.githubusercontent.com/106362356/189496073-b9d4b86e-37e8-44ef-892f-6e18379eda92.png)
![2](https://user-images.githubusercontent.com/106362356/189496076-8b86c33f-73de-4c8b-aa07-e556e1f49389.png)
![3](https://user-images.githubusercontent.com/106362356/189496079-d9b7f289-4ad4-4a2e-961a-c4aa4c88a67e.png)

**Comment by x13a** [comment]
As I said before there is no Android API to block SMS **without implementing the whole SMS app**. It is not in the scope of this app. You have to look at other SMS apps, like QKSMS or Simple SMS. Closing
