### ISSUE TITLE
Not all permissions are asked on the first run

### ISSUE THREAD

**Issue by Efenstor** [x13a/Silence#197]
Thank you for the wonderful app! In the "Extra" settings, "Contacts" is tuned on by default but (at least on Android 12 and probably later) the permission to access contacts is not asked on the first run of the app. When I switch this option off and then on then it is asked okay.

**Comment by x13a** [comment]
It is by design. If the app does not have access to contacts, Android will allow all calls from them.

**Comment by x13a** [comment]
With the exception to Android 10 as I remember.

**Comment by Efenstor** [comment]
Thanks. That behavior is a bit confusing anyway. Why the system asks for the permission when the option is re-enabled? That is no big deal anyway if the function does work as it should.

**Comment by x13a** [comment]
When you disable _Extra > Contacts_ Silence has to block calls from them. To do this it requires Contacts permission.
