### ISSUE TITLE
"Activate" button blocks the texts behind it on the activation page

### ISSUE THREAD

**Issue by yuhuitech** [x13a/Silence#2]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the activation page, **there is an "activate" button blocking the texts behind**. And this page is not scrollable, so I can not see those texts in this circumstance. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.6.2, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that the text behind the "activate" button should be separated from the button.

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app for the first time
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/129442042-34f13bc4-b177-4b5a-93a9-298bba298402.png" alt="copy" width="250"/>

**Environment**

1. Version of Silence : 1.6.2,
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by x13a** [comment]
Closing with your pull request. Thanks)
