### ISSUE TITLE
Is it possible to allow calls on their second attempt in specified interval?

### ISSUE THREAD

**Issue by RadioRambo** [x13a/Silence#207]
block first attempt but allow second attempt onwards.

**Comment by Efenstor** [comment]
Yes, it is possible, just set Repeated Calls > Count to 2 and Minutes to some large value, e.g. 720 (12 hours).

**Comment by RadioRambo** [comment]
It tried that. It isn't working. Maybe that option serves different purpose

**Comment by kamil-cy** [comment]
As @Efenstor said it should work and I'm using this feature. Please specify more info, so maybe we could help.

**Comment by RadioRambo** [comment]
My usecase is whenever I get a call from unknown number (number not saved in contacts), app should silent the call first time. And second time call and more from same number within a day, it should ring.

**Comment by kamil-cy** [comment]
And that's the way it's working for me. If the second call happens before two hours from the first one it passes.

**Comment by kamil-cy** [comment]
And that's the way it's working for me. If the second call happens before two hours from the first one it passes.

**Comment by Efenstor** [comment]
Does it block repeated calls at all or they all pass through no matter the settings? If that's the case then probably you are in the same situation as I was, so I had to create [my own fork](https://github.com/Efenstor/Silence) of Silence and fix this issue myself.

**Comment by RadioRambo** [comment]
@kamil-cy are you blocking or silencing first call? 

@Efenstor  I also tried the forked one too but both results are same. The problem is if settings are unchanged (i.e Disallow call is checked and reject call is checked or even if only only disallow call is checked) everything is working as I intended except instead of silencing first call and ringing second call, it straight away blocks the first call and rings from second call. But if I change settings (disallow call is unchecked and reject call is unchecked but silence call is checked) then all (first, second, third,...)  calls are silenced. 

That is what the bug I'm facing.

**Comment by Efenstor** [comment]
Aha, I see. That is a bug, obviously. I think I can look into it.

**Comment by Efenstor** [comment]
@RadioRambo I am not quite sure, but I think it works: https://github.com/Efenstor/Silence/releases/tag/git230210

**Comment by Efenstor** [comment]
> Sorry for off-topic, but could you please tell me if you are building this apps after installation of android studio and other required software by your hand or you are using such thing like https://github.com/mingchen/docker-android-build-box ?

I've never had any success with anything else but the full Android Studio. I use the Flatpak version, to keep the system clean, and it works fine.

**Comment by RadioRambo** [comment]
@Efenstor Wow. It worked. I cannot thank you enough. Thanks for everything. You are awesome.

**Comment by Efenstor** [comment]
I have further improved the logic of the "Silence call" function (and a bit more): https://github.com/Efenstor/Silence/releases/tag/git230213. I have made a pull request to the master with all of my changes, I hope x13a will accept them.
