### ISSUE TITLE
The "ON"/"OFF" button text is confusing

### ISSUE THREAD

**Issue by KamalW** [x13a/Silence#208]
The button text can be interpreted differently leading to confusion. For example, "ON" can be interpreted like this:
  - Click to active the silence feature
  - Currently the silence feature is active

**Comment by kamil-cy** [comment]
So what changes do you propose?

**Comment by KamalW** [comment]
A simple solution would be to change the button text to unambiguously indicate the click action. So "TURN ON" and "TURN OFF" instead of "ON" and "OFF" would do.
