### ISSUE TITLE
Best app ever created!

### ISSUE THREAD

**Issue by ghost** [x13a/Silence#221]
Works like charm, much thnx!

**Comment by olologin** [comment]
Yep, MIUI has similar functionality, but with much less settings. I was missing it when I switched to google pixel, but then somebody recommended me looking at this app, and it is really irreplaceable. Thanks to the author.

**Comment by alithechemist** [comment]
> Yep, MIUI has similar functionality, but with much less settings. I was missing it when I switched to google pixel, but then somebody recommended me looking at this app, and it is really irreplaceable. Thanks to the author.

I hope you are  using GrapheneOs on a Google Pixel

**Comment by olologin** [comment]
> I hope you are using GrapheneOs on a Google Pixel
Yes, I bought Pixel exactly because of it.
