### ISSUE TITLE
[question] does the app silence calls from numbers not in contacts?

### ISSUE THREAD

**Issue by redcat42** [x13a/Silence#230]
im currently using the built in 'do not disturb' in android 14

this app says, 'allows calls from numbers you have contacted' which would imply it checks the call log not contacts stored on the phone, hence the question, so as to get some clarity

also, if it does silence the calls that are not in contacts, does the call dialog show on screen and does audio playing i.e. for example music paue while the call is being silenced,

thanks

**Comment by x13a** [comment]
There are some modes for this, you can change them in settings. By default it will reject unknown calls without call dialog and a notification will be shown

**Comment by x13a** [comment]
By default it will reject all numbers not in your contacts, but you can extend allowed list for example for number that you already have called, Silence will check the call log for them..

**Comment by redcat42** [comment]
thanks for clearing that up for me, i was a little confused, appreciate it, will try the app, thanks
