### ISSUE TITLE
SIM should only be shown if applicable

### ISSUE THREAD

**Issue by TinfoilSubmarine** [x13a/Silence#237]
I only have one SIM card, so this is extraneous and confusing:
![Screenshot_20240418-091017_Trebuchet~2](https://github.com/x13a/Silence/assets/19600707/48dc1268-66d2-4e0a-b3d8-12b10dfaa3c4)

Same for the SIM menu in the app too.

**Comment by x13a** [comment]
SIM menu has to be shown if your **phone support multi-sim**, even if you have only one active.

**Comment by TinfoilSubmarine** [comment]
Not sure I understand the logic here. Why would we show the SIM menu if there is only one SIM present on the device? Some modern devices are supporting eSIM alongside physical SIM, which is increasing the number of dual-SIM devices available. But this doesn't mean that most users are using those devices as dual-SIM phones.
