### ISSUE TITLE
why is 'Silence' not on google play but all your other apps are?

### ISSUE THREAD

**Issue by redcat42** [x13a/Silence#261]
would be nice to see 'Sience' on google play along with your other apps [https://play.google.com/store/apps/developer?id=lucky0&hl=en-US](https://play.google.com/store/apps/developer?id=lucky0&hl=en-US)

really a great app!

**Comment by x13a** [comment]
Google don't want it to be there cause their permissions policy :(

**Comment by redcat42** [comment]
> Google don't want it to be there cause their permissions policy :(

I can imagine

this guy has kept things simple 

https://play.google.com/store/apps/details?id=com.lifesoftwarelab.android.incomingcallcontrol

maybe two versions, one for plastered and the other for fdroid

but I guess that would be a pain to maintain 

thanks for your work
