### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by oo72vv** [x13a/Silence#29]
Hi, I want to contribute to this project.
Can I send a Pull request for this project?

**Comment by oo72vv** [comment]
Or I want to improve the UI !

**Comment by x13a** [comment]
Hi, please explain what you want to do?

**Comment by oo72vv** [comment]
I want to contribute to improving the user interface of this project.
I think the user interface can be prettier.
And I think it'd be nice to make it brighter to match the app icon mood.
If you allow me, I'll try making it.

**Comment by x13a** [comment]
You can try, but I can't promise that it will be merged) There are two themes, dark and light, depends on `Dark theme` is activated on your device. Anyway without screenshots, it is hard to guess about the result.

**Comment by oo72vv** [comment]
Oh, thank you!😆😆 It's okay if it doesn’t reflect what I do. But I'll try making it!

**Comment by oo72vv** [comment]
I sent a PR! #30

**Comment by x13a** [comment]
Looks nice! Good job, @oo72vv . I can merge it, but will remove delimiters. On mobile we have very limited height and some people may use large fonts too. It results in some switches become out of the view. Plus later, maybe someone will give a good idea for another "allow" option. What do you think of it?

**Comment by oo72vv** [comment]
I'm glad you like it. Thank you!😆 If the delimiters are removed, I think it'll be good to make it more readable with a gap between the "allow" options. And I don't know what you asked. Sorry, can you tell me in more detail? Are you asking me to think of a new option?

**Comment by x13a** [comment]
I was asking about using this theme without delimiters. Will make a release later today. Thanks)

**Comment by oo72vv** [comment]
Aha! Okay, Thank you ❤️
