### ISSUE TITLE
Feature Request - Call Log/Notifications

### ISSUE THREAD

**Issue by TwisX** [x13a/Silence#34]
First off, thanks for this. Really fills the gap with the ability to block unknown callers missing from Android, especially when switching from iPhone.

I think it'd be useful to have a basic blocked call log and to get a silent notification whenever a call is blocked. If I'm expecting a call from a business or someone not in my contacts and I forget to disable the app, it'd be good to have this sort of information available. If nothing else, it'd be satisfying to verify that the app is working and to see all the calls getting blocked.

**Comment by x13a** [comment]
> a basic blocked call log

Blocked calls are available in your `Phone` app's call log.

> get a silent notification

This can be done, I suppose, but no ETA. For now you can try to use apps for automation like `Automate` or `Tasker`, I haven't tested this.

**Comment by TwisX** [comment]
> > a basic blocked call log
> 
> Blocked calls are available in your `Phone` app's call log.
> 
> > get a silent notification
> 
> This can be done, I suppose, but no ETA. For now you can try to use apps for automation like `Automate` / `Tasker` / `MacroDroid`, I haven't tested this.

Oh, blocked calls don't appear to be showing up in my Phone app call log for some reason then.

**Comment by x13a** [comment]
It will be good if you say what is your phone model, android version and phone app.

**Comment by TwisX** [comment]
> It will be good if you say what is your phone model, android version and phone app.

Pixel 5a, CalyxOS (Android 11), AOSP Phone app (version 23).

**Comment by x13a** [comment]
> This can be done, I suppose, but no ETA.

I found that it is enabled by default. All this staff is done by `Phone` app. For example, if you install `Simple Dialer: Phone Calls`, all blocked calls will be in your call log and you will get notification for every blocked call. It seems that `AOSP Phone` do not respect settings.

**Comment by Ilithy** [comment]
If I may comment, I'm in the same situation, I have no blocked call notification, and nothing in my call log, it's a bit problematic. (Pixel 6 pro - grapheneos)

**Comment by x13a** [comment]
Have you tested it with [Simple Dialer](https://f-droid.org/ru/packages/com.simplemobiletools.dialer/)?

**Comment by Ilithy** [comment]
> Have you tested it with [Simple Dialer](https://f-droid.org/ru/packages/com.simplemobiletools.dialer/)?

No, I admit it, I left the basic grapheneos dialer, do you think it would work better with Simple Dialer?

I am always very hesitant to use an unknown application for such an important thing, your application has the huge advantage of not using any access to cellular network and internet, the application does what it wants, I look at that, thank you for the information, I understand that you do not want to complexify your application, it is your right.

**Comment by x13a** [comment]
I am talking about a bug or so in `AOSP Dialer`, cause it does not respect settings. If you will install `Simple Dialer` you will see all blocked calls, they are stored on your device, but not shown by `AOSP Dialer`. About notifications, `Simple Dialer` respect settings and show notification, but `Google Phone` do not show them. 

Any way I will think of some workaround for this.

**Comment by Ilithy** [comment]
@x13a - Thank you for the clarification, and thank you for keeping our problem in mind, it's elegant of you and all my apologies for disturbing you like this. For my part I still hesitate on how to proceed, (I do not wish to use an alternative dialer, too unsure), I have time to think about it ;)

**Comment by x13a** [comment]
@TwisX , @Ilithy I have added notification option in the recent version, make a long click on main toggle (Activate/Deactivate). I have no idea what to do with call log, cause your call log already contains all blocked numbers, but dialer does not show it. Closing it for now for the second time)

**Comment by TinfoilSubmarine** [comment]
Hi all, https://review.lineageos.org/c/LineageOS/android_packages_apps_Dialer/+/384303 has been merged (to both LineageOS 20 and 21) which takes care of this issue. Blocked calls are now displayed in Recents. This only displays calls, so I think having the notification plus this is the best of both worlds :)
