### ISSUE TITLE
Can you explain new permissions?

### ISSUE THREAD

**Issue by smord6** [x13a/Silence#46]
Someone posted on Reddit, worried about "View network connections" permission, apparently in the new version.

See: https://www.reddit.com/r/fossdroid/comments/rub0yp/silence/

Can you put any worries to rest? 

Full quote: 

>Silence
Silence (by lucky) has new permissions. Has anyone had any luck contacting the dev. “View network connections” does not seem to provide any new benefit to the user. The new “Run at startup” can be justified. Changes are “Not provided by developer” and developer is not responsive to emails. I’m not the only person who took notice of these new permissions.

Thanks

**Comment by x13a** [comment]
Hi,

Those new permissions was added by [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager) dependency, I have used to schedule SMS database cleanup. On next release this dependency will be removed and [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler) will be used. As I understand it does not add such additional permissions to the app. This is already done in master branch. Please be patient.

Please do not close this issue, I will close it myself when next release will appear on F-Droid. Thx.
