### ISSUE TITLE
Blocks calls from contacts

### ISSUE THREAD

**Issue by norrinr** [x13a/Silence#5]
Device is a Samsung Galaxy S20 FE with Android 10 and OneUI 2.5. Silence v1.7.1. The app perfectly blocks all calls, including from contacts. When checking permissions under app info, it only had two, neither of them was for contacts. The app never asked me to allow access to contacts, either.

**Comment by x13a** [comment]
You are the second one with this issue.

```text
Hi,

When this add-on is enabled, numbers from the contact list are reset
upon an incoming call.

The call log is empty.
Fresh installation of Android 10 and GApps.
```

Per android documentation contacts permission is not needed:

```text
Further, only calls which are not in the user's contacts are passed for screening, unless the CallScreeningService has been granted Manifest.permission#READ_CONTACTS permission by the user.
```

I can't say for sure why is it not working for you.

**Comment by norrinr** [comment]
Yet Another Call Blocker app has an option that says "Use contacts". It also puts itself as a 'caller ID' app. When I tell it to block * and have "Use contacts" off, it also blocks calls from contacts. If I enable "Use contacts", it asks for contacts permission, and then no longer blocks those calls.

**Comment by norrinr** [comment]
BTW I'd prefer your app because YACB wants to download DBs and check numbers against those and such. Silence is nice and simple.

**Comment by x13a** [comment]
Fixed, please try. You have to manually allow contacts permission in app info > permissions.

**Comment by norrinr** [comment]
It's working great, thank you!

**Comment by norrinr** [comment]
Since the last update via F-Droid (hopefully I'm remembering correctly and it wasn't the previous one), Silence is blocking all calls including contacts again. I have uninstalled and reinstalled to make sure.

**Comment by x13a** [comment]
Are you on Android 10? Have you given it contacts permission?

**Comment by norrinr** [comment]
Yeah, I forgot about having to manually give permissions after reinstalling, until I re-read the thread on Github. Then I deleted my comment :)
