### ISSUE TITLE
No Option To Customize

### ISSUE THREAD

**Issue by TheSoulKeeper** [x13a/Silence#51]
Hi,

How do I customize "Numbers with selected code groups" and "N registered call from the same number within T minutes"? There is no settings option. Its just ON and OFF. So, how do we make our own code groups or customize how many registered calls from the same number within specific duration?

**Comment by x13a** [comment]
Hi,

All is in release notes. This release was fast forward to change WorkManager dependency.

```text
This is not planned release. Subsettings is not implemented.
Some settings descriptions from future. Some will be changed.
```

**Comment by x13a** [comment]
Done in recent version. But code groups settings are not you expect.
