### ISSUE TITLE
Request: SMS filtering

### ISSUE THREAD

**Issue by HugoDeLaRosa80** [x13a/Silence#6]
Hi, thanks for this project. Do you know if there is a similar API for filtering SMS messages also? I'd like to be able to block SMS the same way, if not in contacts, optionally allowing unknown short codes (one time passcodes, etc.), and optionally allowing toll free numbers. 

I would be surprised if you haven't put thoughts into this. Comments? Ideas?

**Comment by x13a** [comment]
Hi,

No, there is no API for this. It can be implemented via.. custom SMS app :(

**Comment by 2k1dmg** [comment]
You can turn on Silent notifications for the Messages application. But this will work for all messages, even from those in Contacts.

[Choose if notifications interrupt you or stay silent](https://support.google.com/android/answer/9079661?hl=en#zippy=%2Cchoose-if-notifications-interrupt-you-or-stay-silent)

**Comment by HugoDeLaRosa80** [comment]
> Hi,
> 
> No, there is no API for this. It can be implemented via.. custom SMS app :(

Thank you. I figured as much when I didn't find any obvious API documentation.
