### ISSUE TITLE
Call blocking not working

### ISSUE THREAD

**Issue by Ilithy** [x13a/Silence#62]
Hi,
I have a problem, Silence does not work at all on my smartphone.

Device: Pixel 6 pro
OS (non Stock): Grapheneos (Android 12) build SQ1D.220105.007.2022011423
Silence version: 1.9.6
Install from: Github
Additionnal infos:
Play Store/Play Service/play framework not installed.
Optimization of the battery deactivate for Silence.

I have tested several configurations, but the calls in masked numbers always pass, and are displayed. Moreover, after a call, the Silence interface is no longer accessible, And is accessible again after a force close.

I made a video of the screen (if it helps):
https://drive.protonmail.com/urls/T2J7Z6TPK4#3Ez5YDKCPU9e

Thank you for your help.

**Comment by x13a** [comment]
Hi,

It is very good that you have made this issue. Before it I thought that `Private numbers` does not get routed to `Call Screening` because of 

```text
Calls with a Call.Details#getHandlePresentation() of TelecomManager#PRESENTATION_RESTRICTED, 
TelecomManager#PRESENTATION_UNKNOWN or TelecomManager#PRESENTATION_PAYPHONE 
presentation are not provided to the CallScreeningService.
```

Fixed in `v1.9.7`. Thanks)

**Comment by Ilithy** [comment]
Thank you for your exemplary responsiveness.

**Comment by Ilithy** [comment]
I just tested, everything works perfectly, the hidden numbers are blocked and redirected immediately to the answering machine, the application interface remains functional and accessible after the call attempts, thank you again, I close the issue.
