### ISSUE TITLE
Deny SMS permission

### ISSUE THREAD

**Issue by daradib** [x13a/Silence#66]
In version 1.8.2, the callback option does not require SMS permission. In version 1.9.0+, the callback option is replaced with contacted and requires SMS permission (see `requestPermissionsForContacted`).

Perhaps contacted can have a subsetting for selecting calls and/or messages similar to the subsetting for selecting code groups. If permission for call logs or SMS is denied, the corresponding subsetting would be unselected.

**Comment by x13a** [comment]
For workaround you can grant needed permissions, check callback option and then revoke SMS permission manually.
Please explain real world use case, what problems do you have with it? 

**This permission is used to check if you have sent a message to the number (eg. contacted).**

**Comment by daradib** [comment]
Hi, thanks for the fast response! In my case, allowing numbers I've called to call me back is useful. However, I rarely message numbers not already in my contacts, and even if so, that messaged number would be unlikely to reply to me by calling. Also, the SMS permission allows access to the contents of current and past SMS messages, e.g., conversations, two factor codes, even if Silence doesn't use it for that purpose. So instead I prefer to deny the permission.

Another workaround, without temporarily granting accessing to SMS, is to uninstall current version, install older version 1.8.2, check callback, and then upgrade.

**Comment by x13a** [comment]
Got it, will add this soon.

**Comment by x13a** [comment]
Done in recent release, will be available soon at F-Droid.
