### ISSUE TITLE
[Question] Github Sponsors

### ISSUE THREAD

**Issue by Ilithy** [x13a/Silence#70]
Hi x13a,
I noticed that there is no way to support you financially on your github repos, it's commendable from you, but we (users) should be able to do it ;-)

I would like to know if you would be willing to join the Github Sponsors program(or Paypal as a fallback solution), I think some of your users (including me) could use this way to show their gratitude, and support your software development.

Thank you very much for your work.

**Comment by Ilithy** [comment]
Ok thank you

**Comment by Ilithy** [comment]
Sorry to come back to this topic, but I don't have any cryptocurrency wallet, so I can't donate, would you be able to add other donation modes, such as:
- Bank transfer (SEPA or not)
- PayPal
- Patreon
- Github Sponsor

My apologies for the inconvenience, thank you.

**Comment by x13a** [comment]
These progressive technologies have left my "resident evil".
