### ISSUE TITLE
[Request] Call blocking scheduler

### ISSUE THREAD

**Issue by Ilithy** [x13a/Silence#74]
It would be very useful to have a scheduler to define days/times (i.e. by choosing the start and end times and the days of the week) when Silence could have different settings.
This would allow to prevent unwanted calls at inappropriate times (weekends, days off, meals, meetings, nights, sleep...), but would let these calls go through the rest of the day (work).

With this, we would need a new option Do not filter hidden numbers. (to go with the request above)

Is it possible to implement it? Thanks

**Comment by x13a** [comment]
About do not block hidden numbers it can be implemented.

But for scheduling I dislike this. I think that the app have to be only
with core functionality, all other things have to be implemented separate.
Silence has the control receiver that can be used to turn it off and on
with a broadcast. Using this and any app for automation scheduling will
work without adding this feature.

**Comment by x13a** [comment]
Please take a look at the ControlReceiver class.

**Comment by Ilithy** [comment]
Thanks for your answer, indeed, it's feasible, but quite (if not) very complex to set up and modify for users, and a real chore if you set several per day (personally I manually activate/deactivate Silence according to my working hours); but I understand what you told me, I won't insist :) For the option of blocking hidden calls, it is useless without the scheduler, users using an automation app will probably not need it, they will only have to disable Silence, because this setting (allow hidden call) is not controllable by an external automation app; and for the others, they will go through the tiles to activate/deactivate Silence (and thus the blocking/deblocking of hidden numbers) Thank you.

**Comment by x13a** [comment]
I am using `Automate` for a long time. Of cause if closed source is not fearing you)

**Comment by Ilithy** [comment]
Thanks but no ;) my smartphone runs grapheneos, without the (google) play services installed, and I don't install any closed source application, currently I'm looking to use [Key Mapper](https://github.com/keymapperorg/KeyMapper) ))

**Comment by x13a** [comment]
Key Mapper is another beast. It is for button processing. You have to look
on Easer or Automation. Both of them are available at F-Droid. But I
haven't used any of them.

**Comment by Ilithy** [comment]
You are right, I try to divert its use, but impossible, to think.

**Comment by Ilithy** [comment]
I looked at these two that you indicated to me, their interfaces are horrible, and for me quite incomprehensible --', I will abandon this idea, but thank you for your help :).
